num_tokens: 8
dim: 48
depth: 8
heads: 8
dim_head: 16
local_attn_heads: 5
nb_features: 80
feature_redraw_interval: 1000
no_generalized_attention: true
reversible: false
ff_chunks: 1
use_scalenorm: false
use_rezero: false
ff_glu: false
emb_dropout: 0.1
ff_dropout: 0.1
attn_dropout: 0.1
local_window_size: 256